### PR TITLE
Import pako in static constructor block

### PR DESCRIPTION
**Pull request by Carifio24**
This PR provides a fix for #53 by adding a piece of code to import the `pako` library and assign it to a variable of the same name. To do this, I created a static `Imports` class and put the relevant `Script.Literal` statements into the class's static constructor. It would be nice to have something more robust in the future, but this promise should resolve before pako is needed in pretty much every case (as an example, the embed link referenced in the issue works fine with this fix).

One thing I'm a bit unsure about is if we want to add `pako` to `package.json` (either at the top level or the engine level), since we're explicitly referencing it. It's already in the top-level `package-lock.json` (line 38324). It's a dependency of `browserify-zlib`, which is a dependency of `node-libs-browser`, which is a dependency of `webpack`, which is a dependency of some of the `vue-cli` packages.

### CODE REVIEW

**Review by pkgw — COMMENTED** [review]
As per our conversation, yeah, we should add pako as an explicit dep.

For what it's worth, I think that the arrow function here is a more modern JavaScript feature than this codebase has required up to this point. But looking at [CanIUse][ciu], it's super well established, and we probably require more modern browsers anyway for all of our WebGL stuff. So I'm not worried about this being a compatibility issue in practice.

[ciu]: https://caniuse.com/arrow-functions

**Comment by Carifio24** [comment]
I'm also not sure what's up with the checks. Per the logs, the error is with adding an icon to the FontAwesome library in the `embed-creator`. That obviously didn't change at all here, and the type error that it's giving just seems wrong (`IconDefinitionOrPack` is defined as `IconDefinition | IconPack`).

**Comment by pkgw** [comment]
I got an email about FontAwesome 6 coming out recently, so my guess is that we're pulling in a new version of that dep and it's breaking something. We might need to restrict the version that we use for a little while if there's some breakage in a new release ... or maybe we're using something in a wonky way that's no longer allowed.

**Comment by Carifio24** [comment]
FontAwesome 6 was released 10 days ago, so I suspect you're right and that's the culprit. I'll see if I can get this working with some more specific pins, and then look into what we need to do to move on to FA6.

**Comment by Carifio24** [comment]
Pinning `@fortawesome/fontawesome-svg-core` to `~1.2.28` seems to have done the trick as far as FontAwesome goes. I suspect that the `^1.2.28` pin was picking up `1.3.0`, which was released 8 days ago and likely is expecting FA6.

There's now an issue with the actual engine tests and `pako` that I'm not seeing locally, so I'll see what's up with that.

**Comment by Carifio24** [comment]
So I think what's happening is basically what we were thinking won't happen in the wild - in the test, the `import` promise hasn't resolved before the tests run. This wasn't an issue in the test before because `pako` is grabbed there via a [script tag](https://github.com/WorldWideTelescope/wwt-webgl-engine/blob/master/engine/tests/tests.html#L7). After hacking with `engine/src/index.js` a bit, it looks like `pako` defined inside `$exports` is shadowing the window-level `pako`.

One way around this is could be to check `typeof window !== "undefined" && "pako" in window` before importing pako (for scoping purposes, we'd then define the pako in `$exports` to be the global value). This will avoid the import if we're in a browser environment where we've already imported pako from a CDN, but will trigger the import otherwise. It feels hack-y to me, but it should work.

**Comment by Carifio24** [comment]
I've implemented the workaround, and added a comment explaining why we can't create a helper function to do this given the library name (it looks like we'd need C# 10 in order to pull that off). While I was at it, I changed the arrow function to a regular anonymous function.

The BrowserStack test failed the first time through. Based on the logs it looks like the connection between BrowserStack and the CI app got disrupted, and everything was fine the second time through.

**Pull request merged**
